# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Toast
email: robokopp@fernwerk.net
description: > # this means to ignore newlines until "baseurl:"
  Toast is a square shaped slice of white bread that was roasted to yield a crispy texture. Toast can be consumed as it is or with various toppings. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username:
github_username:  robokopp

# Build settings
markdown: kramdown

defaults:
  - scope:
      type: pages
    values:
      subtitle: This manual covers toast-v1.0.0
